# Generated by Django 4.2.4 on 2023-11-25 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
        ('member', '0002_project_projectfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.challenge'),
        ),
    ]
